version: "3.9"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=adminEMT
     - MONGO_INITDB_ROOT_PASSWORD=passwordEMT

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql_root_password"
      MYSQL_DATABASE: "keycloak"
      MYSQL_USER: "keycloak"
      MYSQL_PASSWORD: "mysql_password"

  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    container_name: keycloak
    ports:
      - 8080:8080
      - 8443:8443
    restart: unless-stopped
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"

      # Using MySQL as an external database
      DB_VENDOR: "mysql"
      DB_ADDR: "mysql"        # Use the service name defined in this Docker Compose file
      DB_PORT: "3306"
      DB_DATABASE: "keycloak"
      DB_USER: "keycloak"
      DB_PASSWORD: "mysql_password"  # Use the password set in the MySQL service
